[package]
name = "rocrate"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
oneormany = { version = "1.0.1", features = ["serde"], path = "../oom" }
iref = { version = "4.2.0", features = ["serde"] }
indexmap = { version = "2.5.0", features = ["serde"] }
serde_json = "1.0.151"
miette = { version = "7.6.0", features = ["derive"] }
thiserror = "2.0.19"

[dev-dependencies]
miette = { version = "7.6.0", features = ["fancy"] }
rstest = "0.26.1"
