name: 🦆 Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci-pipeline:
    permissions:
      contents: read
      pull-requests: write
      actions: read
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
       
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest
          locked: true
      - name: 📎Linting
        run: cargo clippy --workspace -- -W clippy::pedantic
      - name: Run tests
        run: cargo nextest run --workspace --no-fail-fast
      - name: Install cargo-tarpaulin
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-tarpaulin
          locked: true
      - name: Run coverage
        run: cargo tarpaulin --workspace --out Xml --exclude-files tests/* tests/**/* crates/**/tests/**/* crates/**/tests/* examples/* examples/**/* crates/**/examples/**/* crates/**/examples/* crates/conformance/**/*
      - name: Code Coverage Summary Report
        if: runner.os == 'linux'
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "cobertura.xml"
          badge: true
          hide_branch_rate: false
          hide_complexity: true # as it is not supported by tarpaulin
          format: "markdown"
          output: "both"

      - name: Add Coverage PR Comment
        if: runner.os == 'linux' && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Write to Job Summary
        if: runner.os == 'linux'
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY