on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

name: 🚀 Publish
permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - run: cargo publish --all-features --token ${{secrets.CRATES_TOKEN}}